### ISSUE TITLE
‘mmdet’ disappearanced and KeyError

### ISSUE THREAD

**Issue by ToneZe** [DDGRCF/FCOSF#1]
pip install -v -e .
Successfully uninstalled mmdet
    [3/3] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /root/FCOSF/build/temp.linux-x86_64-3.8/mmdet/ops/convex/src/convex_cuda.o.d -DWITH_CUDA -I/usr/local/lib/python3.8/dist-packages/torch/include -I/usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.8/dist-packages/torch/include/TH -I/usr/local/lib/python3.8/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.8 -c -c /root/FCOSF/mmdet/ops/convex/src/convex_cuda.cu -o /root/FCOSF/build/temp.linux-x86_64-3.8/mmdet/ops/convex/src/convex_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=convex_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 -std=c++14
    creating build/lib.linux-x86_64-3.8/mmdet/ops/convex
    x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 /root/FCOSF/build/temp.linux-x86_64-3.8/mmdet/ops/convex/src/convex_cpu.o /root/FCOSF/build/temp.linux-x86_64-3.8/mmdet/ops/convex/src/convex_cuda.o /root/FCOSF/build/temp.linux-x86_64-3.8/mmdet/ops/convex/src/convex_ext.o -L/usr/local/lib/python3.8/dist-packages/torch/lib -L/usr/local/cuda/lib64 -L/usr/lib/x86_64-linux-gnu -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.8/mmdet/ops/convex/convex_ext.cpython-38-x86_64-linux-gnu.so
WARNING: Ignoring invalid distribution -cv (/usr/local/lib/python3.8/dist-packages)
WARNING: Ignoring invalid distribution -mcv (/usr/local/lib/python3.8/dist-packages)
WARNING: Ignoring invalid distribution - (/usr/local/lib/python3.8/dist-packages)
Successfully installed mmdet
But  mmdet is not in 'pip list' 

Then by 'pip install mmdet' and  'python ./tools/train.py  configs/fcosf/fcosf_r50.py'
/usr/local/lib/python3.8/dist-packages/mmdet/models/builder.py:51: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
  warnings.warn(
Traceback (most recent call last):
  File "./tools/train.py", line 154, in <module>
    main()
  File "./tools/train.py", line 126, in main
    model = build_detector(
  File "/usr/local/lib/python3.8/dist-packages/mmdet/models/builder.py", line 58, in build_detector
    return DETECTORS.build(
  File "/usr/local/lib/python3.8/dist-packages/mmcv/utils/registry.py", line 215, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'FCOSOBB is not in the models registry'

**Comment by DDGRCF** [comment]
Did you follow docs/install.md to install the repo?

ToneZe ***@***.***> 于2023年9月30日周六 03:43写道：
